version: "3"
services:
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/frontend
  #   depends_on:
  #     - backend
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: server
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./:/backend
  #   depends_on:
  #     - db
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nestjs_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - sai
    restart: always

networks:
  sai:
    driver: bridge

volumes:
  database-data: